<?php
header('Content-Type: application/octet-stream');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST');
header('Access-Control-Allow-Headers: Content-Type');

require_once 'config.php';
require_once 'helpers.php';
require_once 'validators.php';

class LeadExporter {
    private $config;
    private $helpers;
    private $validators;

    public function __construct() {
        $this->config = new Config();
        $this->helpers = new Helpers();
        $this->validators = new Validators();
    }

    public function exportLeads($leads, $format, $filename = null) {
        if (empty($filename)) {
            $filename = 'leads_' . date('Y-m-d_H-i-s');
        }

        switch (strtolower($format)) {
            case 'csv':
                return $this->exportToCSV($leads, $filename);
            case 'excel':
                return $this->exportToExcel($leads, $filename);
            case 'json':
                return $this->exportToJSON($leads, $filename);
            default:
                throw new Exception('Unsupported export format: ' . $format);
        }
    }

    /**
     * Export leads to CSV format
     */
    private function exportToCSV($leads, $filename) {
        $filepath = $this->config->storage['export_path'] . $filename . '.csv';
        
        $file = fopen($filepath, 'w');
        if (!$file) {
            throw new Exception('Could not create CSV file');
        }

        // Write CSV header
        $headers = [
            'Name',
            'Company',
            'Position',
            'Email',
            'Phone',
            'Location',
            'Website',
            'Source',
            'Quality Score',
            'Quality Category',
            'Timestamp'
        ];
        fputcsv($file, $headers, $this->config->export['csv_delimiter'], $this->config->export['csv_enclosure']);

        // Write lead data
        foreach ($leads as $lead) {
            $qualityScore = $this->validators->calculateQualityScore($lead);
            $qualityCategory = $this->validators->getQualityCategory($lead);
            
            $row = [
                $lead['name'] ?? '',
                $lead['company'] ?? '',
                $lead['position'] ?? '',
                $lead['email'] ?? '',
                $lead['phone'] ?? '',
                $lead['location'] ?? '',
                $lead['website'] ?? '',
                $lead['source'] ?? '',
                $qualityScore,
                $qualityCategory,
                $lead['timestamp'] ?? date('Y-m-d H:i:s')
            ];
            
            fputcsv($file, $row, $this->config->export['csv_delimiter'], $this->config->export['csv_enclosure']);
        }

        fclose($file);

        // Set headers for download
        header('Content-Type: text/csv');
        header('Content-Disposition: attachment; filename="' . $filename . '.csv"');
        header('Content-Length: ' . filesize($filepath));

        // Output file content
        readfile($filepath);
        unlink($filepath); // Clean up

        return true;
    }

    /**
     * Export leads to Excel format
     */
    private function exportToExcel($leads, $filename) {
        $filepath = $this->config->storage['export_path'] . $filename . '.xlsx';
        
        // Create new Spreadsheet object
        $spreadsheet = new PhpOffice\PhpSpreadsheet\Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();

        // Set document properties
        $spreadsheet->getProperties()
            ->setCreator($this->config->export['excel_creator'])
            ->setTitle($this->config->export['excel_title'])
            ->setSubject('Generated Leads')
            ->setDescription('Leads generated by Lead Generation System')
            ->setKeywords('leads, business, contacts')
            ->setCategory('Business Data');

        // Set headers
        $headers = [
            'A1' => 'Name',
            'B1' => 'Company',
            'C1' => 'Position',
            'D1' => 'Email',
            'E1' => 'Phone',
            'F1' => 'Location',
            'G1' => 'Website',
            'H1' => 'Source',
            'I1' => 'Quality Score',
            'J1' => 'Quality Category',
            'K1' => 'Timestamp'
        ];

        foreach ($headers as $cell => $value) {
            $sheet->setCellValue($cell, $value);
        }

        // Style headers
        $headerStyle = [
            'font' => [
                'bold' => true,
                'color' => ['rgb' => 'FFFFFF']
            ],
            'fill' => [
                'fillType' => \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID,
                'startColor' => ['rgb' => '4472C4']
            ],
            'alignment' => [
                'horizontal' => \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER
            ]
        ];

        $sheet->getStyle('A1:K1')->applyFromArray($headerStyle);

        // Add data rows
        $row = 2;
        foreach ($leads as $lead) {
            $qualityScore = $this->validators->calculateQualityScore($lead);
            $qualityCategory = $this->validators->getQualityCategory($lead);
            
            $sheet->setCellValue('A' . $row, $lead['name'] ?? '');
            $sheet->setCellValue('B' . $row, $lead['company'] ?? '');
            $sheet->setCellValue('C' . $row, $lead['position'] ?? '');
            $sheet->setCellValue('D' . $row, $lead['email'] ?? '');
            $sheet->setCellValue('E' . $row, $lead['phone'] ?? '');
            $sheet->setCellValue('F' . $row, $lead['location'] ?? '');
            $sheet->setCellValue('G' . $row, $lead['website'] ?? '');
            $sheet->setCellValue('H' . $row, $lead['source'] ?? '');
            $sheet->setCellValue('I' . $row, $qualityScore);
            $sheet->setCellValue('J' . $row, $qualityCategory);
            $sheet->setCellValue('K' . $row, $lead['timestamp'] ?? date('Y-m-d H:i:s'));

            // Add conditional formatting for quality scores
            if ($qualityScore >= 90) {
                $sheet->getStyle('I' . $row)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)->getStartColor()->setRGB('90EE90');
            } elseif ($qualityScore >= 70) {
                $sheet->getStyle('I' . $row)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)->getStartColor()->setRGB('FFFF99');
            } elseif ($qualityScore >= 50) {
                $sheet->getStyle('I' . $row)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)->getStartColor()->setRGB('FFB366');
            } else {
                $sheet->getStyle('I' . $row)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)->getStartColor()->setRGB('FF9999');
            }

            $row++;
        }

        // Auto-size columns
        foreach (range('A', 'K') as $column) {
            $sheet->getColumnDimension($column)->setAutoSize(true);
        }

        // Add filters
        $sheet->setAutoFilter('A1:K' . ($row - 1));

        // Create Excel file
        $writer = new PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
        $writer->save($filepath);

        // Set headers for download
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment; filename="' . $filename . '.xlsx"');
        header('Content-Length: ' . filesize($filepath));

        // Output file content
        readfile($filepath);
        unlink($filepath); // Clean up

        return true;
    }

    /**
     * Export leads to JSON format
     */
    private function exportToJSON($leads, $filename) {
        $filepath = $this->config->storage['export_path'] . $filename . '.json';
        
        // Prepare data for export
        $exportData = [
            'metadata' => [
                'export_date' => date('Y-m-d H:i:s'),
                'total_leads' => count($leads),
                'format' => 'JSON',
                'version' => '1.0'
            ],
            'statistics' => $this->validators->validateLeadsBatch($leads),
            'leads' => []
        ];

        // Process each lead
        foreach ($leads as $lead) {
            $qualityScore = $this->validators->calculateQualityScore($lead);
            $qualityCategory = $this->validators->getQualityCategory($lead);
            
            $exportData['leads'][] = [
                'name' => $lead['name'] ?? '',
                'company' => $lead['company'] ?? '',
                'position' => $lead['position'] ?? '',
                'email' => $lead['email'] ?? '',
                'phone' => $lead['phone'] ?? '',
                'location' => $lead['location'] ?? '',
                'website' => $lead['website'] ?? '',
                'source' => $lead['source'] ?? '',
                'quality' => [
                    'score' => $qualityScore,
                    'category' => $qualityCategory,
                    'is_high_quality' => $this->validators->isHighQualityLead($lead)
                ],
                'validation' => $this->validators->validateLead($lead),
                'timestamp' => $lead['timestamp'] ?? date('Y-m-d H:i:s')
            ];
        }

        // Write JSON file
        $jsonContent = $this->config->export['json_pretty_print'] 
            ? json_encode($exportData, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)
            : json_encode($exportData);

        if (file_put_contents($filepath, $jsonContent) === false) {
            throw new Exception('Could not create JSON file');
        }

        // Set headers for download
        header('Content-Type: application/json');
        header('Content-Disposition: attachment; filename="' . $filename . '.json"');
        header('Content-Length: ' . filesize($filepath));

        // Output file content
        readfile($filepath);
        unlink($filepath); // Clean up

        return true;
    }

    /**
     * Generate summary report
     */
    public function generateSummaryReport($leads) {
        $stats = $this->validators->validateLeadsBatch($leads);
        
        $report = [
            'summary' => [
                'total_leads' => $stats['total'],
                'valid_leads' => $stats['valid'],
                'high_quality_leads' => $stats['high_quality'],
                'leads_with_email' => $stats['with_email'],
                'leads_with_phone' => $stats['with_phone'],
                'leads_with_both' => $stats['with_both'],
                'quality_distribution' => $stats['quality_distribution']
            ],
            'sources' => [],
            'top_companies' => [],
            'top_locations' => []
        ];

        // Analyze sources
        $sources = [];
        foreach ($leads as $lead) {
            $source = $lead['source'] ?? 'Unknown';
            $sources[$source] = ($sources[$source] ?? 0) + 1;
        }
        arsort($sources);
        $report['sources'] = array_slice($sources, 0, 10, true);

        // Analyze companies
        $companies = [];
        foreach ($leads as $lead) {
            if (!empty($lead['company'])) {
                $company = $lead['company'];
                $companies[$company] = ($companies[$company] ?? 0) + 1;
            }
        }
        arsort($companies);
        $report['top_companies'] = array_slice($companies, 0, 10, true);

        // Analyze locations
        $locations = [];
        foreach ($leads as $lead) {
            if (!empty($lead['location'])) {
                $location = $lead['location'];
                $locations[$location] = ($locations[$location] ?? 0) + 1;
            }
        }
        arsort($locations);
        $report['top_locations'] = array_slice($locations, 0, 10, true);

        return $report;
    }

    /**
     * Export summary report to HTML
     */
    public function exportSummaryToHTML($leads, $filename) {
        $report = $this->generateSummaryReport($leads);
        
        $html = '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lead Generation Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { background: #4472C4; color: white; padding: 20px; text-align: center; }
        .section { margin: 20px 0; padding: 15px; border: 1px solid #ddd; }
        .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; }
        .stat-card { background: #f8f9fa; padding: 15px; border-radius: 5px; text-align: center; }
        .stat-number { font-size: 2em; font-weight: bold; color: #4472C4; }
        table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #f8f9fa; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Lead Generation Report</h1>
        <p>Generated on ' . date('Y-m-d H:i:s') . '</p>
    </div>';

        // Summary Statistics
        $html .= '<div class="section">
        <h2>Summary Statistics</h2>
        <div class="stats">
            <div class="stat-card">
                <div class="stat-number">' . $report['summary']['total_leads'] . '</div>
                <div>Total Leads</div>
            </div>
            <div class="stat-card">
                <div class="stat-number">' . $report['summary']['valid_leads'] . '</div>
                <div>Valid Leads</div>
            </div>
            <div class="stat-card">
                <div class="stat-number">' . $report['summary']['high_quality_leads'] . '</div>
                <div>High Quality</div>
            </div>
            <div class="stat-card">
                <div class="stat-number">' . $report['summary']['leads_with_email'] . '</div>
                <div>With Email</div>
            </div>
        </div>
    </div>';

        // Quality Distribution
        $html .= '<div class="section">
        <h2>Quality Distribution</h2>
        <table>
            <tr><th>Quality Level</th><th>Count</th><th>Percentage</th></tr>';
        
        foreach ($report['summary']['quality_distribution'] as $quality => $count) {
            $percentage = $report['summary']['total_leads'] > 0 ? round(($count / $report['summary']['total_leads']) * 100, 1) : 0;
            $html .= '<tr><td>' . $quality . '</td><td>' . $count . '</td><td>' . $percentage . '%</td></tr>';
        }
        
        $html .= '</table></div>';

        // Top Sources
        if (!empty($report['sources'])) {
            $html .= '<div class="section">
            <h2>Top Data Sources</h2>
            <table>
                <tr><th>Source</th><th>Leads Count</th></tr>';
            
            foreach ($report['sources'] as $source => $count) {
                $html .= '<tr><td>' . htmlspecialchars($source) . '</td><td>' . $count . '</td></tr>';
            }
            
            $html .= '</table></div>';
        }

        // Top Companies
        if (!empty($report['top_companies'])) {
            $html .= '<div class="section">
            <h2>Top Companies</h2>
            <table>
                <tr><th>Company</th><th>Leads Count</th></tr>';
            
            foreach ($report['top_companies'] as $company => $count) {
                $html .= '<tr><td>' . htmlspecialchars($company) . '</td><td>' . $count . '</td></tr>';
            }
            
            $html .= '</table></div>';
        }

        // Top Locations
        if (!empty($report['top_locations'])) {
            $html .= '<div class="section">
            <h2>Top Locations</h2>
            <table>
                <tr><th>Location</th><th>Leads Count</th></tr>';
            
            foreach ($report['top_locations'] as $location => $count) {
                $html .= '<tr><td>' . htmlspecialchars($location) . '</td><td>' . $count . '</td></tr>';
            }
            
            $html .= '</table></div>';
        }

        $html .= '</body></html>';

        $filepath = $this->config->storage['export_path'] . $filename . '_report.html';
        file_put_contents($filepath, $html);

        return $filepath;
    }
}

// Handle export request
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        $exporter = new LeadExporter();
        
        // Get leads from the generation process
        $generator = new LeadGenerator();
        $result = $generator->generateLeads($_POST);
        
        if (!$result['success']) {
            throw new Exception($result['message']);
        }

        $format = $_POST['export_format'] ?? 'csv';
        $filename = 'leads_' . date('Y-m-d_H-i-s');
        
        $exporter->exportLeads($result['leads'], $format, $filename);
        
    } catch (Exception $e) {
        header('Content-Type: application/json');
        echo json_encode([
            'success' => false,
            'message' => $e->getMessage()
        ]);
    }
} else {
    header('Content-Type: application/json');
    echo json_encode([
        'success' => false,
        'message' => 'Invalid request method'
    ]);
}
?> 